#pragma once

#include <cstdint>
#include "common/types.h"

namespace lt {

enum class ExecIntentType : uint8_t {
    PLACE_ORDER = 0,
    CANCEL_ORDER,
    CANCEL_ALL,
    REPLACE_ORDER,
    HEARTBEAT,
};

// OrderType is defined in common/types.h

// Fixed-size POD for SPSC queue transport (T2 -> T3)
struct ExecIntent {
    ExecIntentType type = ExecIntentType::PLACE_ORDER;
    AssetId asset_id;
    AssetId market_id;          // condition/market ID
    OrderId client_order_id;    // stable correlation ID (generated by T2)
    OrderId exchange_order_id;  // for cancel: the exchange-assigned order ID
    Side side = Side::BID;
    Price_t price = 0;          // 10000x fixed-point
    Qty_t size = 0;             // number of shares
    OrderType order_type = OrderType::GTC;
    uint32_t intent_id = 0;     // unique ID for correlation
    Timestamp_ns created_ts = 0;
    Timestamp_ns recv_ts = 0;     // M7: original event receive timestamp for pipeline latency
    bool neg_risk = false;      // determines which exchange contract for signing
    uint16_t fee_rate_bps = 0;  // maker fee rate from CLOB (part of signed payload)
    int64_t expiration = 0;     // GTD expiration timestamp (0 = no expiry)
};

}  // namespace lt
