#pragma once

#include <atomic>
#include <unordered_map>

#include "common/types.h"

namespace lt {

// FIFO PnL tracker: matches buys against sells in FIFO order to compute
// realized trading P&L. Accumulates across all markets for the session.
//
// Thread safety:
//   - record_fill() / reverse_fill(): T1 only (ExecStateStore)
//   - settle_asset(): T2 only (after market_killed, no more T1 fills)
//   - realized_pnl(): T6 reads (atomic, lock-free)
//
// Fixed-size circular buffers per asset. No heap allocation on fill path.

struct FifoEntry {
    Price_t price = 0;      // fill price (fp4)
    Qty_t remaining = 0;    // remaining unmatched qty (fp6)
};

struct AssetPnlState {
    static constexpr int kMaxEntries = 256;

    FifoEntry longs[kMaxEntries];   // BUY entries awaiting SELL match
    int long_head = 0;
    int long_count = 0;

    FifoEntry shorts[kMaxEntries];  // SELL entries awaiting BUY match
    int short_head = 0;
    int short_count = 0;

    bool settled = false;

    void push_long(Price_t price, Qty_t qty) {
        if (long_count >= kMaxEntries) return;  // overflow — drop
        int idx = (long_head + long_count) % kMaxEntries;
        longs[idx] = {price, qty};
        ++long_count;
    }

    void push_short(Price_t price, Qty_t qty) {
        if (short_count >= kMaxEntries) return;
        int idx = (short_head + short_count) % kMaxEntries;
        shorts[idx] = {price, qty};
        ++short_count;
    }

    FifoEntry& front_long() { return longs[long_head]; }
    FifoEntry& front_short() { return shorts[short_head]; }

    void pop_long() {
        long_head = (long_head + 1) % kMaxEntries;
        --long_count;
    }

    void pop_short() {
        short_head = (short_head + 1) % kMaxEntries;
        --short_count;
    }
};

class PnlTracker {
public:
    // Register a complement pair for cross-asset matching (dual-bid model).
    // 1 UP + 1 DOWN = $1 → PnL = (10000 - up_price - down_price) × qty.
    void register_pair(const AssetId& up, const AssetId& down) {
        complement_.emplace(up, down);
        complement_.emplace(down, up);
        // Pre-create state entries so cross-matching works regardless of fill order.
        // Called at startup before trading threads start — no synchronization needed.
        states_[up];
        states_[down];
    }

    // Record a confirmed fill. T1 calls this from ExecStateStore::record_fill().
    // Returns the PnL delta generated by this fill (for reversal tracking).
    int64_t record_fill(const AssetId& asset_id, Side side, Price_t price, Qty_t size) {
        auto& state = states_[asset_id];
        if (state.settled) return 0;

        int64_t fill_pnl = 0;

        if (side == Side::BID) {
            // BUY: match against open shorts (FIFO) — same-asset matching
            Qty_t remaining = size;
            while (remaining > 0 && state.short_count > 0) {
                auto& entry = state.front_short();
                Qty_t matched = std::min(remaining, entry.remaining);
                int64_t pnl = (static_cast<int64_t>(entry.price) - price) * matched / kPriceScale;
                fill_pnl += pnl;
                entry.remaining -= matched;
                remaining -= matched;
                if (entry.remaining == 0) state.pop_short();
            }
            if (remaining > 0) state.push_long(price, remaining);

            // Cross-asset paired matching: 1 UP long + 1 DOWN long = $1
            auto comp_it = complement_.find(asset_id);
            if (comp_it != complement_.end()) {
                auto comp_state_it = states_.find(comp_it->second);
                if (comp_state_it != states_.end() && !comp_state_it->second.settled) {
                    auto& comp_state = comp_state_it->second;
                    while (state.long_count > 0 && comp_state.long_count > 0) {
                        auto& this_entry = state.front_long();
                        auto& comp_entry = comp_state.front_long();
                        Qty_t matched = std::min(this_entry.remaining, comp_entry.remaining);
                        // PnL = ($1 - cost_this - cost_complement) × matched
                        int64_t pnl = (static_cast<int64_t>(kPriceScale) - this_entry.price - comp_entry.price)
                                      * matched / kPriceScale;
                        fill_pnl += pnl;
                        this_entry.remaining -= matched;
                        comp_entry.remaining -= matched;
                        if (this_entry.remaining == 0) state.pop_long();
                        if (comp_entry.remaining == 0) comp_state.pop_long();
                    }
                }
            }
        } else {
            // SELL: match against open longs (FIFO)
            Qty_t remaining = size;
            while (remaining > 0 && state.long_count > 0) {
                auto& entry = state.front_long();
                Qty_t matched = std::min(remaining, entry.remaining);
                int64_t pnl = (static_cast<int64_t>(price) - entry.price) * matched / kPriceScale;
                fill_pnl += pnl;
                entry.remaining -= matched;
                remaining -= matched;
                if (entry.remaining == 0) state.pop_long();
            }
            if (remaining > 0) state.push_short(price, remaining);
        }

        realized_pnl_.fetch_add(fill_pnl, std::memory_order_relaxed);
        return fill_pnl;
    }

    // Reverse a fill that FAILED on-chain. Subtracts the exact PnL delta
    // that was recorded during the original fill — no FIFO interaction,
    // no phantom positions or PnL drift.
    void reverse_fill(int64_t original_pnl_delta) {
        realized_pnl_.fetch_add(-original_pnl_delta, std::memory_order_relaxed);
    }

    // Settle all remaining position for an asset at a fixed price.
    // Called by T2 on MARKET_RESOLVED or price kill. Safe because fills
    // have stopped for this asset (market_killed = true).
    void settle_asset(const AssetId& asset_id, Price_t settlement_price) {
        auto it = states_.find(asset_id);
        if (it == states_.end()) return;
        auto& state = it->second;
        if (state.settled) return;

        // Close all remaining longs: PnL = (settlement - entry_price) × qty
        while (state.long_count > 0) {
            auto& entry = state.front_long();
            int64_t pnl = (static_cast<int64_t>(settlement_price) - entry.price)
                          * entry.remaining / kPriceScale;
            realized_pnl_.fetch_add(pnl, std::memory_order_relaxed);
            state.pop_long();
        }

        // Close all remaining shorts: PnL = (entry_price - settlement) × qty
        while (state.short_count > 0) {
            auto& entry = state.front_short();
            int64_t pnl = (static_cast<int64_t>(entry.price) - settlement_price)
                          * entry.remaining / kPriceScale;
            realized_pnl_.fetch_add(pnl, std::memory_order_relaxed);
            state.pop_short();
        }

        state.settled = true;
    }

    // Total realized PnL in micro-USDC (fp6). Lock-free atomic read.
    int64_t realized_pnl() const {
        return realized_pnl_.load(std::memory_order_relaxed);
    }

private:
    std::unordered_map<AssetId, AssetPnlState, AssetIdHash> states_;
    std::unordered_map<AssetId, AssetId, AssetIdHash> complement_;  // cross-asset pair mapping
    std::atomic<int64_t> realized_pnl_{0};
};

}  // namespace lt
